controller_manager:
  ros__parameters:
    update_rate: 500

    twist_controller:
      type: prox2f_control/TwistController

    gripper_command_controller:
      type: e2f_controllers/GripperCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

twist_controller:
  ros__parameters:
    update_rate: 10 # not Hz, but divisor
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    kinematics:
      end_effector_link: tcp
    enabled_axes:
      - true
      - true
      - true
      - false
      - true
      - true
    filter_coefficient: 0.1
    safety:
      linear_speed_limit: 0.1
      angular_speed_limit: 0.5

gripper_command_controller:
  ros__parameters:
    joint: grp_stroke

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: tool0
    topic_name: ft_data
