controller_manager:
  ros__parameters:
    update_rate: 60

    prox2f_arm_controller:
      type: velocity_controllers/JointGroupVelocityController

    prox2f_gripper_controller:
      type: effort_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

prox2f_arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: velocity

prox2f_gripper_controller:
  ros__parameters:
    joint: grp_stroke
    goal_tolerance: 0.005
    allow_stalling: true
    stall_velocity_threshold: 0.002
    stall_timeout: 1.0
    gains:
      grp_stroke:
        p: -30.0
        i: -0.2
        d: -0.2
        i_clamp: 2.0

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: tool0
    topic_name: ft_data
