controller_manager:
  ros__parameters:
    update_rate: 60

    prox2f_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_command_controller:
      type: e2f_controllers/GripperCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    io_and_status_controller:
      type: ur_controllers/GPIOController

    speed_scaling_state_broadcaster:
      type: ur_controllers/SpeedScalingStateBroadcaster

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

prox2f_arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    gains:
      shoulder_pan_joint:
        ff_velocity_scale: 1.0
      shoulder_lift_joint:
        ff_velocity_scale: 1.0
      elbow_joint:
        ff_velocity_scale: 1.0
      wrist_1_joint:
        ff_velocity_scale: 1.0
      wrist_2_joint:
        ff_velocity_scale: 1.0
      wrist_3_joint:
        ff_velocity_scale: 1.0

gripper_command_controller:
  ros__parameters:
    joint: grp_stroke

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: tool0
    topic_name: ft_data
